name: nextjs

type: 'nodejs:14'

dependencies:
    nodejs:
        yarn: "1.22.17"
        pm2: "5.2.0"

build:
    flavor: none

variables:
    env:
        NODE_OPTIONS: --max-old-space-size=1536

size: L

resources:
    base_memory: 1024
    memory_ratio: 1024

hooks:
    build: |
        # 1. Build dependencies.
        set -e
        yarn --frozen-lockfile

        # ln -s env/.env .env
        chmod +x update-env.sh

    deploy: |
        . update-env.sh

    post_deploy: |
        # 3. Rebuild and restart the pm2 process, now with the available backend api.
        yarn build
web:
    commands:
        start: |
            # 2. Build and start the pm2 process, using the default http://localhost:1337 as backend API.
            NEXT_PUBLIC_API_URL=http://localhost:1337
            PREVIEW_SECRET=mysecret
            yarn build
            pm2 start npm --no-daemon --watch --name "foodadvisor-client" -- start -- -p $PORT
disk: 512

mounts:
    /.next:
        source: local
        source_path: 'next'
    /.pm2:
        source: local
        source_path: 'next'

    # env:
    #     source: local
    #     source_path: 'env'